export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_SORT = "FETCH_DATA_SORT";
export const SHOW_ITEM = "SHOW_ITEM";
export const ADD_TO_TABLE = "ADD_TO_TABLE";
export const TABLE_SEARCH = "TABLE_SEARCH";